# name: GitHub Pages

# on:
#   push:
#   workflow_dispatch:

# jobs:
#   deploy:
#     runs-on: ubuntu-22.04
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           submodules: true  # Fetch Hugo themes (true OR recursive)
#           fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

#       - name: Setup Hugo
#         uses: peaceiris/actions-hugo@v2
#         with:
#           hugo-version: '0.91.2'
#           # extended: true

#       - name: Build
#         run: hugo --minify

#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           PERSONAL_TOKEN: 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
#           EXTERNAL_REPOSITORY: caoxianfei1/caoxianfei1.github.io
#           PUBLISH_BRANCH: master
#           PUBLISH_DIR: ./public
#           commit_message: ${{ github.event.head_commit.message }}

name: github pages

on:
  push:
    branches:
      - master  # Set a branch that will trigger a deployment
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.101.0'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # if: github.ref == 'refs/heads/main'
        with:
          personal_token: ${{ secrets.HUGO_DEPLOY_PERSONAL_TOKEN }}
          # deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          EXTERNAL_REPOSITORY: caoxianfei1/caoxianfei1.github.io
          PUBLISH_BRANCH: master
          publish_dir: ./public
